name: tdc
channels:
  - conda-forge
dependencies:
  - python=3.7
  - rdkit
  - deepchem
  - scikit-learn
  - pip
  - pip:
    - PyTDC
    - xgboost
    - mordred
    - gensim
    - tensorflow~=2.4
    - git+https://github.com/samoturk/mol2vec
    - PubChemPy
